# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 22:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_degree', models.CharField(choices=[('F', 'Undergraduate'), ('M', 'Graduate')], max_length=50)),
                ('edu_degree_title', models.CharField(max_length=50)),
                ('edu_degree_cgpa', models.CharField(max_length=2)),
                ('edu_degree_university', models.CharField(max_length=30)),
                ('edu_degree_location', models.CharField(max_length=30)),
                ('edu_certification_title', models.CharField(max_length=50)),
                ('edu_certification_body', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_department', models.CharField(max_length=20)),
                ('fac_hire_date', models.DateField(default=datetime.date.today)),
                ('fac_professor_rank', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intern_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(default='Windsor', max_length=20)),
                ('province', models.CharField(default='Ontario', max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='Canada', max_length=20)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('contact_position', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('company_website', models.URLField()),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_type', models.CharField(max_length=50)),
                ('intern_discription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=100)),
                ('job_responsibilities', models.CharField(max_length=50)),
                ('job_requirements', models.CharField(max_length=50)),
                ('job_salary', models.IntegerField()),
                ('job_status', models.CharField(choices=[('open', 'Open'), ('unopened', 'Unopened'), ('closed', 'Closed')], max_length=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Intern_Info')),
                ('intern_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Internship')),
            ],
        ),
        migrations.CreateModel(
            name='Job_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_group_type', models.CharField(max_length=20)),
                ('job_group_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester_registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(choices=[('F', 'Fall'), ('W', 'Winter')], max_length=1)),
                ('semester_year', models.DateField()),
                ('semester_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_telephone', models.IntegerField()),
                ('stu_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('stu_status', models.CharField(choices=[('I', 'International Resident'), ('P', 'Permanent Resident')], default='I', max_length=1)),
                ('stu_current_past', models.CharField(choices=[('C', 'Current Student'), ('P', 'Past Student')], max_length=1)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Semester_registered')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Job_groups'),
        ),
        migrations.AddField(
            model_name='education',
            name='stu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
    ]
