# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-18 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_registered',
            name='semester_year',
            field=models.IntegerField(),
        ),
    ]
