# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170718_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_department',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_hire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='fac_professor_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Job'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Semester_registered'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_current_past',
            field=models.CharField(choices=[('C', 'Current Student'), ('P', 'Past Student')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_telephone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
