# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170806_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_info',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='intern_info',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='intern_info',
            name='contact_position',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='intern_info',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern_info',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
