# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170815_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_professor_rank',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
