# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170815_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_certification_body',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_certification_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(default=0),
        ),
    ]
