# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170822_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_hire_date',
            field=models.DateField(),
        ),
    ]
