# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staff_sta_hire_date'),
        ('app', '0005_auto_20170823_1115'),
    ]

    operations = [
    ]
