from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^contact$', views.contact,name='contact'),
    url(r'^education/$', views.education,name='education'),
    # url(r'^internship_info$', views.internship_info,name='internship_info'),
    url(r'^internship_info$', views.InternshipInfoListView.as_view(),name='internship_info'),
    url(r'^internship_type$', views.internship_type,name='internship_type'),
    url(r'^job_record$', views.job_record,name='job_record'),
    url(r'^job_group$', views.job_group,name='job_group'),
    url(r'^student$', views.student,name='student'),
    url(r'^faculty$', views.faculty, name='faculty'),
    url(r'^staff$',views.staff,name='staff'),
    url(r'^semester$',views.SemesterView.as_view(),name='semester'),
    url(r'^education/add$', views.EducationCreateView.as_view(), name='add_education'),
    url(r'^education/update/(?P<pk>\d+)$', views.EducationUpdateView.as_view(), name='update_education'),
    url(r'^education/delete/(?P<pk>\d+)$', views.EducationDeleteView.as_view(), name='delete_education'),
    url(r'^internship_info/add$', views.InternshipInfoCreateView.as_view(), name='add_internship_info'),
    url(r'^internship_info/update/(?P<pk>\d+)$', views.InternshipInfoUpdateView.as_view(), name='update_internship_info'),
    url(r'^internship_info/delete/(?P<pk>\d+)$', views.InternshipInfoDeleteView.as_view(), name='delete_internship_info'),
    # url(r'^add_internship_type$', views.add_internship_type, name='add_internship_type'),
    url(r'^job_record/add$', views.JobRecordCreateView.as_view(), name='add_job_record'),
    url(r'^job_record/update/(?P<pk>\d+)$', views.JobRecordUpdateView.as_view(), name='update_job_record'),
    url(r'^job_record/delete/(?P<pk>\d+)$', views.JobRecordDeleteView.as_view(), name='delete_job_record'),
    url(r'^job_group/add$', views.JobGroupCreateView.as_view(), name='add_job_group'),
    url(r'^student/add$', views.StudentCreateView.as_view(), name='add_student'),
    url(r'^student/update/(?P<pk>\d+)$', views.StudentUpdateView.as_view(), name='update_student'),
    url(r'^student/delete/(?P<pk>\d+)$', views.StudentDeleteView.as_view(), name='delete_student'),
    url(r'^faculty/add$', views.FacultyCreateView.as_view(), name='add_faculty'),
    url(r'^faculty/update/(?P<pk>\d+)$', views.FacultyUpdateView.as_view(), name='update_faculty'),
    url(r'^faculty/delete/(?P<pk>\d+)$', views.FacultyDeleteView.as_view(), name='delete_faculty'),
    url(r'^staff/add$', views.StaffCreateView.as_view(), name='add_staff'),
    url(r'^staff/update/(?P<pk>\d+)$', views.StaffUpdateView.as_view(), name='update_staff'),
    url(r'^staff/delete/(?P<pk>\d+)$', views.Staff, name='delete_staff'),
    url(r'^semester/add$', views.SemesterCreateView.as_view(), name='add_semester'),
    url(r'^report$',views.report, name="report"),
    url(r'logout/',views.user_logout, name='logout'),
]